### ISSUE TITLE
Endpoint Testing: GetBoroughs, e2e and service unit

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/ae-zoning-api#144]
# Description

Write e2e tests and service unit tests for the `GetBoroughs` endpoint

Acceptance criteria
- Service unit tests
  - [ ] should test the service returns a getBoroughQueryResponseSchema compliant object
- e3e tests
  - [ ] should test the happy path returns a 200 and a response body with a getBoroughQueryResponseSchema compliant object
  - [ ] should test database errors return a 500 and a response body with the correct error data

**Comment by pratishta** [comment]
@TangoYankee Should we also be testing for 400 errors since that's documented as one of the possible error responses?

**Comment by TangoYankee** [comment]
> @TangoYankee The documentation also has 400 as a possible error response for this endpoint-- what's a possible bad request? Should we be testing for it?

Hypothetically, the [client could malform their request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400), such as using invalid syntax. I've been hoping Nest would automatically recognize when requests are malformed and return a 400. My hope was that we would be able to write test scenarios for this case. My approach was to use supertest to set a request header to an invalid value. Unfortunately, the test was still returning a 200. So, I've resigned to ignore that test case for now.

After we get tests written to handle the explicit errors, it might be worthwhile to circle back to the 400 caused by malformed requests. But for now, I'm ignoring that scenario to allow us to focus on the known scenarios.

You might be wondering whether we should remove that 400 from the documentation or be more explicit in handling malformed requests. We want to keep the 400 because redocly recommends it and we agree. We don't yet want to handle malformed requests explicitly because that requires digging into the guts of Nest. So, here we are, in limbo, ignoring it as a test case.
