### ISSUE TITLE
Add Project fund-related schemas to API Schema

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/ae-zoning-api#212]
# Description
Implement the schemas related to project funding. These include the [`project_checkbook`](https://github.com/NYCPlanning/ae-data-flow/blob/f513c4a44751497b48a6926a3047da2b1ead9ec9/sql/commitment.sql#L144) and [`project_fund`](https://github.com/NYCPlanning/ae-data-flow/blob/f513c4a44751497b48a6926a3047da2b1ead9ec9/sql/commitment.sql#L170) tables. It also includes the [`fund_category`](https://github.com/NYCPlanning/ae-data-flow/blob/f513c4a44751497b48a6926a3047da2b1ead9ec9/sql/commitment.sql#L152) and [`project_fund_stage`](https://github.com/NYCPlanning/ae-data-flow/blob/f513c4a44751497b48a6926a3047da2b1ead9ec9/sql/commitment.sql#L163) enums. 

[Full ERD](https://github.com/NYCPlanning/ae-data-flow/blob/commitment-erd/sql/commitment-erd.png) for reference

## Acceptance Criteria
- [x] A `project_fund_stage` enum exists, matches the options listed in the reference ERD/sql, and is exported from the project schema file (this makes it visible to future migrations. I am prescriptive on which file to use because it will only be used by project schemas and colocating the definition with its only use makes it easier to read.)
- [x] A `fund_category` enum exists, matches the options listed in the reference ERD/sql, and is exported from the file where it is defined (this makes it visible to future migrations. I'm not prescriptive on which file should hold the enum because it needs to be shared across two different schemas.)
- [x] A `project_fund` schema exists and mirrors the columns documented in the ERD/reference SQL table
- [x] A `project_checkbook` schema exists and mirrors the columns documented in the ERD/reference SQL table
- [x] The database columns use snake_case and the javascript variables use camelCase

## Related tickets
Blocked by the schemas created in #210

**Comment by TylerMatteo** [comment]
@bmarchena you can start working on this if you're waiting for feedback on #210. You can just branch off your branch for that one.
