### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/ae-zoning-api#217]
# Description
Based on the capital commitment ERD, we will design an API to make the data accessible. This is a precursor to the Open API documentation, which will provide more specifics on how to access the data and what data to expect in return. The result of this ticket will be a list of endpoints, data they will accept as part of the request, and data they should expect in the response. "data" may refer to the HTTP method, HTTP headers, query strings, url parameters, response type, etc. The acceptance criteria below outline key features of the API. However, it is not an exhaustive list and features may be added. Though, feature addition should be done prudently to avoid feature creep.

## API Use Cases
Below is a list of use cases that our endpoints will have to support. These should inform the list of endpoints and their details to be compiled for this Issue.

- [x] Retrieve a paginated list of capital projects within a given geography
- [x] Retrieve detailed information about one capital project with a given ID
- [x] Retrieve a paginated list of commitments associated with a given project by project ID
- [x] Retrieve MVTs of mapped capital projects

**Comment by pratishta** [comment]
Endpoints
- `/projects`
- `/projects/<z>/<x>/<y>/.pbf`
- `projects/<mc_id>/<proj_id>` -> returns object `{description, min_date, max_date, sum_commitments, managing_code, project_id, sponsor_initials[], sponsor_budget_project_types[]}` 
- `projects/<mc_id>/<proj_id>/commitments` -> returns an array of commitments `{[{id, commitment_type, date, bl_code, bl_id, sponsor_agency_initials, budget_type, total_value}]}` (all stuff from commitments table, join agency_budget, join commitment_fund)
- `/boroughs/<borough_id>/community-districts/<cd_id>/projects`
- `/city-council-districts/<ccd_id>/projects`
- `/agencies`

**Comment by TangoYankee** [comment]
# Expaning on the endpoints

## /projects
Description: a paginated list of project meta data useful for looking up specific projects
Methods: GET
Status codes: 
- 200, data is successfully returned
- 400, invalid request
- 500, server error
Query parameters:
- limit, default to 20, maximum 100
- offset, default to 0, no maximum
Response Body:
- projects: 
   - id
   - managing_code
- limit
- total
- offset

## /projects/<z>/<x>/<y>.pbf

**Comment by TangoYankee** [comment]
Should we actually be calling these "capital-projects", instead of just "projects"? I'm realizing project is a really generic name.

**Comment by TangoYankee** [comment]
We have two big questions about the MVT endpoints. 

1) First, should filtering be accomplished on the front end- meaning that we only need to support endpoints that offer tiles for the whole viewport. 

2) Second, we need to share MVT data for fills and labels. Do we want to go with the approach of offering multiple endpoints that each serves a single geometry type. Or, do we want to offer one endpoint that collects the geometries together? I know how to do the first method and I think you were experimenting with the second method?

Either way, it would probably be good to move forward with the other endpoints while we figure out the tiles.

**Comment by TangoYankee** [comment]
Reading the endpoints back, I think we don't actually need `/capital-projects`. The mockups only list projects within a geography- this is captured by the district-specific project lists. I do think a `/capital-projects` endpoint will be helpful if we want to offer a more sophisticated way to filter and access capital projects. However, we don't actually know what we want to support with this endpoint. Do we want to offer spatial filters? Do we want to show more details than just the id? We don't know. 

**For now, I think we should remove the `/capital-projects` endpoint**; it's easier to wait and do it the way want the first time, rather than try to change an endpoint we've already made public.

**Comment by TangoYankee** [comment]
I didn't know what was happening with `csv` and `shape` downloads. So, I ended up not messing with that.

**Comment by TylerMatteo** [comment]
> Should we actually be calling these "capital-projects", instead of just "projects"? I'm realizing project is a really generic name. I updated the endpoints with this naming but I'm not married to it yet. Same with `capital-commitments`

I'm definitely supportive of favoring `capital-projects` over `projects`. It strikes me as an easy way to future proof against potential name collision (_lookin' at you, ZAP)_. "Commitments" are _probably_ specific enough on their own but it wouldn't hurt to do `capital-commitments` for the sake of consistency.

**Comment by TylerMatteo** [comment]
>     1. First, should filtering be accomplished on the front end- meaning that we only need to support endpoints that offer tiles for the whole viewport?

Let's move forward with the assumption we will be filtering the tiled data on the front end - it seems like a good use for Deck's [MaskExtension](https://deck.gl/docs/api-reference/extensions/mask-extension). If that proves impossible or impracticable, we can revisit filtering tiles at the API level.

**Comment by TangoYankee** [comment]
> I'm definitely supportive of favoring capital-projects over projects. It strikes me as an easy way to future proof against potential name collision (lookin' at you, ZAP). "Commitments" are probably specific enough on their own but it wouldn't hurt to do capital-commitments for the sake of consistency.

I'm thinking we apply the `capital-projects` and `capital-commitments` refactor to the table names, as well. It will keep things consistent from the public api to the database.

**Comment by TangoYankee** [comment]
@TylerMatteo I realized the original list completed omitted the MVT endpoint for community and city council districts. I updated the ticket with an /community-districts/{z}/{x}/{y}.pbf and an /city-council-districts/{z}/{x}/{y}.pbf endpoint

**Comment by TangoYankee** [comment]
@TylerMatteo Also, realizing that I forgot an endpoint to list all city council districts. This will be required for the city council district geography selector

**Comment by TangoYankee** [comment]
> Still waiting on James for clarity on how exactly our app will handle that use case, so we can de-prioritize this until we know more, just wanted to capture it.

Okay, we'll brainstorm implementation once we have more guidance on product
