### ISSUE TITLE
Implement findCommunityDistrictsByBoroughId endpoint

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/ae-zoning-api#246]
## Acceptance criteria
- [x] Implement the `findCommunityDistrictsByBoroughId` endpoint in compliance with #236
- [x] Write end to end tests
- [x] Write unit tests

## helpful code: 
[the zoning districts domain](https://github.com/NYCPlanning/ae-zoning-api/tree/main/src/zoning-district) 

## Related tickets
- blocked by #236

**Comment by dhochbaum-dcp** [comment]
Hi Horatio, the work I did so far on this is here: https://github.com/NYCPlanning/ae-zoning-api/tree/246/Implement-findCommunityDistrictsByBoroughId-endpoint-2
