### ISSUE TITLE
  Implement findCapitalProjectsByBoroughIdCommunityDistrictId endpoint 

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/ae-zoning-api#247]
## Acceptance criteria
- [x] Implement the `findCapitalProjectsByBoroughIdCommunityDistrictId` endpoint in compliance with #237
   - should be part of the `borough` domain folder
- [x] Write end to end tests
- [x] Write unit tests
- [x] Add geospatial index

## helpful code: 
[the tax lot domain](https://github.com/NYCPlanning/ae-zoning-api/tree/main/src/tax-lot) 

## Related tickets
- blocked by #237, #334

**Comment by TylerMatteo** [comment]
Unfortunately didn't get too far with this but I did start a branch that someone can pick up: `247/projects-by-comm-district`. It has a commit for adding the constraints @TangoYankee mentions above.

**Comment by TangoYankee** [comment]
@pratishta this ticket is affected by an incorrect geometry type. Community districts are supposed to be multipolygons. But, the 'lift' column is incorrectly typed as a 'point'. There are two fixes associated:
1) Fix the column itself
2) Remove the ["patch"](https://github.com/NYCPlanning/ae-data-flow/blob/capital-planning-flow/sql/populate_tables.sql#L478) in the data flow
    - This patch was put in to coerce the geometry into a point and just get the data flow working with the database until we could correct it.

**Comment by pratishta** [comment]
Updated the draft PR with most of the work so far here: https://github.com/NYCPlanning/ae-zoning-api/pull/327#issuecomment-2177213282
