### ISSUE TITLE
Implement findCommunityDistrictTiles endpoint

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/ae-zoning-api#252]
## Acceptance criteria
- [ ] Implement the `findCommunityDistrictTiles` endpoint in compliance with #243
   - should be part of a `community-district` domain folder
- [ ] Write end to end tests
- [ ] Write unit tests

## helpful code:
[tax lots with experimental tile endpoints](https://github.com/NYCPlanning/ae-zoning-api/tree/f2508c4d1059b35b1e5e295c10566545094c7982/src/tax-lot) combined with guidance from @TylerMatteo on key modifications that combine the separate geometries into a single endpoint

## Related tickets
- blocked by #243

**Comment by pratishta** [comment]
The separate geometries mentioned refer specifically to the polygon geom (the actual geometry of the community district) and the label geom (a point geometry for the label of that district). The experimental tax lots tile branch has the fill and the label tiles fetched in separate endpoints. We should have the fill and label be fetched from the same endpoint which involves combining two layers into a  single MVT to be consumed by deck.gl. https://stackoverflow.com/questions/66283798/get-separate-layers-in-an-mvt
