### ISSUE TITLE
OpenAPI Documentation: Update Community District Schema boroughId pattern 

### ISSUE THREAD

**Issue by horatiorosa** [NYCPlanning/ae-zoning-api#307]
#### Description:
While running the [unit test](src/borough/borough.service.spec.ts#39) for `/boroughs/{boroughId}/community-districts`, the communityDistrict object that was returned did not conform to the expected result of a single digit from 0 to 9. The current pattern in the OpenAPI documentation, `\b[1-9]\b`, the `\b` is included with the boroughId (ex: `\b2\b`)

##### `CommunityDIstrict` schema:
<img width="393" alt="Screenshot 2024-06-06 at 11 29 50 AM" src="https://github.com/NYCPlanning/ae-zoning-api/assets/11340947/f5ab70f6-8bee-4d1a-9f93-294eb9de12b5">

#### Response for `CommunityDIstrict`:
<img width="448" alt="Screenshot 2024-06-06 at 11 30 06 AM" src="https://github.com/NYCPlanning/ae-zoning-api/assets/11340947/3b955847-cb37-41a4-beae-b3bc603c184c">

#### Acceptance criteria
- [ ] Update the pattern for the  `CommunityDIstrict` schema to remove the `\b` so the `boroughId` is a single digit, 0 - 9 as shown in the image below:
<img width="413" alt="Screenshot 2024-06-06 at 11 30 16 AM" src="https://github.com/NYCPlanning/ae-zoning-api/assets/11340947/4a5bb11d-3049-490b-9dce-cc8ee8f9c2ff">

**Comment by TangoYankee** [comment]
@horatiorosa are there other parameters that use the `/b` delimiter? Could we scope this ticket to refactor any parameters that use the `/b` pattern?

**Comment by horatiorosa** [comment]
In this instance, this is a necessary and low level scope creep. 
The add'l lines have been taken care of.
