### ISSUE TITLE
Portfolio Analytics

### ISSUE THREAD

**Issue by jpiacentinidcp** [NYCPlanning/ae-zoning-api#32]
As part of a multi-sprint effort to evaluate our portfolio of apps, we would like to compile high level user analytics for each app. This effort will help us understand current usage and will inform how we prioritize future work across the portfolio.

For each of the apps listed below, we would like the following information for the previous 1 year:

1. total visits and overall usage
2. unique users
3. sessions per user
4. pageviews and pages per session
5. average session duration
6. bounce rate
7. top 10 landing pages and breakdown for each (sessions, % new sessions, new users, etc.)
8. top 10 pages visited and breakdown for each (sessions, % new sessions, new users, etc.)
9. Top 5 interactions / buttons or other UI elements interacted with and breakdown for each (sessions, % new sessions, new users, etc.)

The list of apps is as follows:

1. Applicant Maps​
2. Capital Planning Explorer
3. CEQR​
4. ​Community District Needs​
5. Community District Profiles
6. ​Equitable Development Data Explorer
7. ​Metro Region Explorer​
8. NYC Streets Map
9. ​Online Zoning Resolution​
10. Population FactFinder​
11. Tax Lot Selector​
12. Waterfront Access Map
13. ZAP Applicant Portal
14. ZAP Dynamics 365
15. ZAP LUP Portal
16. ZAP Search
17. ZoLa

**Comment by dhochbaum-dcp** [comment]
- I did not include information for Community District Needs, as it's not relevant
- Tax Lot Selector and ZAP Dynamics 365 are not tagged
- ZAP LUP Portal is a subsection of ZAP Search and is included in those results



[Portfolio_Analytics_1_1_2023_-_11_7_2023.pdf](https://github.com/NYCPlanning/ae-zoning-api/files/13301839/Portfolio_Analytics_1_1_2023_-_11_7_2023.pdf)

Info 1-8 is included for the rest of the apps in the attached document.  #9 would require extra work, please let me know if during your analysis you would like me to pull it for a specific site.

As always, I am happy to help answer any questions or provide any analysis you would like.

**Comment by jpiacentinidcp** [comment]
@dhochbaum-dcp  Thanks a ton! This is super helpful!
