### ISSUE TITLE
Sort city council districts

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/ae-zoning-api#368]
# Description
It would be convenient if the `Select` inputs in the front end are sorted by district number in ascending order. We want to perform this sorting in the back end so that it is available to all applications that use the zoning api.

![Image](https://github.com/user-attachments/assets/ccc4dda4-9cad-486e-950d-fbc9ab9833df)

## Acceptance criteria
- [x] The OpenAPI documentation is updated to with an 'order' variable that specifies that the city council districts are sorted by their IDs, as if they are numbers
- [x] The SQL/drizzle query for city council districts returns them sorted by their ids, as if they are numbers. (city council district '2' should come before '17'). 
  - Order is ascending.
- [x] The JSON response includes an `order` key with a value of `id`

**Comment by TangoYankee** [comment]
> We could just use `sort()` so we don't explicitly have to convert them `arr.sort(function(a, b){return b-a});`

This comment was made when we still planned to sort the data on the front end. Now that we are using the api to sort the data, it will be SQL and not JavaScript doing the sorting.
